language: groovy
jdk:
- oraclejdk11
before_script:
- chmod +x gradlew
- echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
script:
- ./gradlew check
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn clean cobertura:cobertura coveralls:report